#!/bin/bash



THEORY_LIST=(41000000)

DISTRIBUTION_LIST=(
"ATLAS_TTBAR_13P6TEV_TOT_X-SEC"
"ATLAS_TTBAR_13TEV_HADR_DIF_MTTBAR-YTTBAR-NORM"
"ATLAS_TTBAR_13TEV_HADR_DIF_YTTBAR-NORM"
"ATLAS_TTBAR_13TEV_HADR_DIF_MTTBAR-NORM"
"ATLAS_TTBAR_13TEV_LJ_DIF_MTTBAR-NORM"
"ATLAS_TTBAR_13TEV_LJ_DIF_PTT-NORM"
"ATLAS_TTBAR_13TEV_LJ_DIF_YT-NORM"
"ATLAS_TTBAR_13TEV_LJ_DIF_YTTBAR-NORM"
"ATLAS_TTBAR_13TEV_LJ_DIF_PTT-YT-NORM"
"ATLAS_TTBAR_13TEV_LJ_DIF_MTTBAR-PTT-NORM"
"ATLAS_TTBAR_13TEV_TOT_X-SEC"
"ATLAS_TTBAR_5TEV_TOT_X-SEC"
"ATLAS_TTBAR_7TEV_TOT_X-SEC"
"ATLAS_TTBAR_8TEV_2L_DIF_YTTBAR-NORM"
"ATLAS_TTBAR_8TEV_2L_DIF_MTTBAR-NORM"
"ATLAS_TTBAR_8TEV_LJ_DIF_MTTBAR-NORM"
"ATLAS_TTBAR_8TEV_LJ_DIF_PTT-NORM"
"ATLAS_TTBAR_8TEV_LJ_DIF_YT-NORM"
"ATLAS_TTBAR_8TEV_LJ_DIF_YTTBAR-NORM"
"ATLAS_TTBAR_8TEV_TOT_X-SEC"
"CMS_TTBAR_13P6TEV_TOT_X-SEC"
"CMS_TTBAR_13TEV_2L_138FB-1_DIF_MTTBAR"
"CMS_TTBAR_13TEV_2L_138FB-1_DIF_PTT"
"CMS_TTBAR_13TEV_2L_138FB-1_DIF_YT"
"CMS_TTBAR_13TEV_2L_138FB-1_DIF_MTTBAR-YTTBAR"
"CMS_TTBAR_13TEV_2L_DIF_PTT-NORM"
"CMS_TTBAR_13TEV_2L_DIF_MTTBAR-NORM"
"CMS_TTBAR_13TEV_2L_DIF_YT-NORM"
"CMS_TTBAR_13TEV_2L_DIF_YTTBAR-NORM"
"CMS_TTBAR_13TEV_LJ_DIF_YT-NORM"
"CMS_TTBAR_13TEV_LJ_DIF_MTTBAR-NORM"
"CMS_TTBAR_13TEV_LJ_DIF_YTTBAR-NORM"
"CMS_TTBAR_13TEV_LJ_DIF_MTTBAR-YTTBAR-NORM"
"CMS_TTBAR_13TEV_LJ_DIF_PTT-NORM"
"CMS_TTBAR_13TEV_TOT_X-SEC"
"CMS_TTBAR_5TEV_TOT_X-SEC"
"CMS_TTBAR_7TEV_TOT_X-SEC"
"CMS_TTBAR_8TEV_2L_DIF_PTT-YT-NORM"
"CMS_TTBAR_8TEV_2L_DIF_MTTBAR-YT-NORM"
"CMS_TTBAR_8TEV_2L_DIF_MTTBAR-YTTBAR-NORM"
"CMS_TTBAR_8TEV_LJ_DIF_PTT-NORM"
"CMS_TTBAR_8TEV_LJ_DIF_YT-NORM"
"CMS_TTBAR_8TEV_LJ_DIF_YTTBAR-NORM"
"CMS_TTBAR_8TEV_LJ_DIF_MTTBAR-NORM"
"CMS_TTBAR_8TEV_TOT_X-SEC"
"DYE866_Z0_800GEV_DW_RATIO_PDXSECRATIO"
"DYE866_Z0_800GEV_PXSEC"
"DYE605_Z0_38P8GEV_DW_PXSEC"
"DYE906_Z0_120GEV_DW_PDXSECRATIO"
"CDF_Z0_1P96TEV_ZRAP"
"D0_Z0_1P96TEV_ZRAP"
"D0_WPWM_1P96TEV_ASY"
"ATLAS_WPWM_7TEV_36PB_ETA"
"ATLAS_Z0_7TEV_36PB_ETA"
"ATLAS_Z0_7TEV_49FB_HIMASS"
"ATLAS_Z0_7TEV_LOMASS_M"
"ATLAS_WPWM_7TEV_46FB_CC-ETA"
"ATLAS_Z0_7TEV_46FB_CC-Y"
"ATLAS_Z0_7TEV_46FB_CF-Y"
"ATLAS_Z0_8TEV_HIMASS_M-Y"
"ATLAS_Z0_8TEV_LOWMASS_M-Y"
"ATLAS_Z0_13TEV_TOT"
"ATLAS_WPWM_13TEV_TOT"
"ATLAS_WJ_8TEV_WP-PT"
"ATLAS_WJ_8TEV_WM-PT"
"ATLAS_Z0J_8TEV_PT-M"
"ATLAS_Z0J_8TEV_PT-Y"
"ATLAS_1JET_8TEV_R06_PTY"
"ATLAS_2JET_7TEV_R06_M12Y"
"ATLAS_PH_13TEV_XSEC"
"ATLAS_SINGLETOP_7TEV_TCHANNEL-XSEC"
"ATLAS_SINGLETOP_13TEV_TCHANNEL-XSEC"
"ATLAS_SINGLETOP_7TEV_T-Y-NORM"
"ATLAS_SINGLETOP_7TEV_TBAR-Y-NORM"
"ATLAS_SINGLETOP_8TEV_T-RAP-NORM"
"ATLAS_SINGLETOP_8TEV_TBAR-RAP-NORM"
"CMS_WPWM_7TEV_ELECTRON_ASY"
"CMS_WPWM_7TEV_MUON_ASY"
"CMS_Z0_7TEV_DIMUON_2D"
"CMS_WPWM_8TEV_MUON_Y"
"CMS_Z0J_8TEV_PT-Y"
"CMS_2JET_7TEV_M12Y"
"CMS_1JET_8TEV_PTY"
"CMS_SINGLETOP_7TEV_TCHANNEL-XSEC"
"CMS_SINGLETOP_8TEV_TCHANNEL-XSEC"
"CMS_SINGLETOP_13TEV_TCHANNEL-XSEC"
"LHCB_Z0_7TEV_DIELECTRON_Y"
"LHCB_Z0_8TEV_DIELECTRON_Y"
"LHCB_WPWM_7TEV_MUON_Y"
"LHCB_Z0_7TEV_MUON_Y"
"LHCB_WPWM_8TEV_MUON_Y"
"LHCB_Z0_8TEV_MUON_Y"
"LHCB_Z0_13TEV_DIMUON-Y"
"LHCB_Z0_13TEV_DIELECTRON-Y"
"NNPDF_POS_2P24GEV_F2U"
"NNPDF_POS_2P24GEV_F2D"
"NNPDF_POS_2P24GEV_F2S"
"NNPDF_POS_2P24GEV_FLL"
"NNPDF_POS_2P24GEV_DYU"
"NNPDF_POS_2P24GEV_DYD"
"NNPDF_POS_2P24GEV_DYS"
"NNPDF_POS_2P24GEV_F2C"
"NNPDF_POS_2P24GEV_XUQ"
"NNPDF_POS_2P24GEV_XUB"
"NNPDF_POS_2P24GEV_XDQ"
"NNPDF_POS_2P24GEV_XDB"
"NNPDF_POS_2P24GEV_XSQ"
"NNPDF_POS_2P24GEV_XSB"
"NNPDF_POS_2P24GEV_XGL"
"NNPDF_INTEG_3GEV_XT8"
"NNPDF_INTEG_3GEV_XT3"
)

# Define the wrapper script for running smefit
WRAPPER_SCRIPT="run_pineko.sh"

# Create the wrapper script
cat <<EOL > $WRAPPER_SCRIPT
#!/bin/bash
# Wrapper script for executing pineko

THEORY=\$1
DISTRIBUTION=\$2

pineko theory opcards \$THEORY \$DISTRIBUTION --overwrite
pineko theory ekos \$THEORY \$DISTRIBUTION  --overwrite
pineko theory fks \$THEORY \$DISTRIBUTION --overwrite
EOL

# Make the wrapper script executable
chmod +x $WRAPPER_SCRIPT

# Create the HTCondor submit description file
cat <<EOL > submit_pineko.submit
# HTCondor submit file

universe = vanilla
executable = $WRAPPER_SCRIPT

# Transfer input files (the runcards)
arguments = \$(Item1) \$(Item2)

+UseOS                  = "el9"
+JobCategory            = "medium"
request_cpus   = 32
request_memory = 128G
getenv = true
accounting_group = smefit

# Define log, output, and error files
log = logs/\$(Cluster)_\$(Process).log
output = logs/\$(Cluster)_\$(Process).out
error = logs/\$(Cluster)_\$(Process).err

max_idle = 20

# Queue jobs for each runcard
queue Item1, Item2 from (
EOL

# Append runcard list to the submit file
for THEORY in "${THEORY_LIST[@]}"; do
  for DIST in "${DISTRIBUTION_LIST[@]}"; do

    echo "$THEORY $DIST" >> submit_pineko.submit
  done
done

echo ")" >> submit_pineko.submit

# Submit the jobs
#condor_submit submit_pineko.submit


